# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_login.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 430)
        Dialog.setStyleSheet("\n"
"")
        self.back = QtWidgets.QPushButton(Dialog)
        self.back.setGeometry(QtCore.QRect(650, 60, 121, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.back.setFont(font)
        self.back.setStyleSheet("")
        self.back.setObjectName("back")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(230, 0, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.one = QtWidgets.QPushButton(Dialog)
        self.one.setGeometry(QtCore.QRect(250, 60, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.one.setFont(font)
        self.one.setObjectName("one")
        self.two = QtWidgets.QPushButton(Dialog)
        self.two.setGeometry(QtCore.QRect(350, 60, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.two.setFont(font)
        self.two.setObjectName("two")
        self.three = QtWidgets.QPushButton(Dialog)
        self.three.setGeometry(QtCore.QRect(450, 60, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.three.setFont(font)
        self.three.setObjectName("three")
        self.four = QtWidgets.QPushButton(Dialog)
        self.four.setGeometry(QtCore.QRect(250, 150, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.four.setFont(font)
        self.four.setObjectName("four")
        self.five = QtWidgets.QPushButton(Dialog)
        self.five.setGeometry(QtCore.QRect(350, 150, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.five.setFont(font)
        self.five.setObjectName("five")
        self.six = QtWidgets.QPushButton(Dialog)
        self.six.setGeometry(QtCore.QRect(450, 150, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.six.setFont(font)
        self.six.setObjectName("six")
        self.seven = QtWidgets.QPushButton(Dialog)
        self.seven.setGeometry(QtCore.QRect(250, 240, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.seven.setFont(font)
        self.seven.setObjectName("seven")
        self.clear = QtWidgets.QPushButton(Dialog)
        self.clear.setGeometry(QtCore.QRect(250, 330, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.clear.setFont(font)
        self.clear.setObjectName("clear")
        self.eight = QtWidgets.QPushButton(Dialog)
        self.eight.setGeometry(QtCore.QRect(350, 240, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.eight.setFont(font)
        self.eight.setObjectName("eight")
        self.nine = QtWidgets.QPushButton(Dialog)
        self.nine.setGeometry(QtCore.QRect(450, 240, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.nine.setFont(font)
        self.nine.setObjectName("nine")
        self.zero = QtWidgets.QPushButton(Dialog)
        self.zero.setGeometry(QtCore.QRect(350, 330, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.zero.setFont(font)
        self.zero.setObjectName("zero")
        self.enter = QtWidgets.QPushButton(Dialog)
        self.enter.setGeometry(QtCore.QRect(450, 330, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.enter.setFont(font)
        self.enter.setObjectName("enter")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.back.setText(_translate("Dialog", "Return"))
        self.label.setText(_translate("Dialog", "Admin Login"))
        self.one.setText(_translate("Dialog", "1"))
        self.two.setText(_translate("Dialog", "2"))
        self.three.setText(_translate("Dialog", "3"))
        self.four.setText(_translate("Dialog", "4"))
        self.five.setText(_translate("Dialog", "5"))
        self.six.setText(_translate("Dialog", "6"))
        self.seven.setText(_translate("Dialog", "7"))
        self.clear.setText(_translate("Dialog", "Clear"))
        self.eight.setText(_translate("Dialog", "8"))
        self.nine.setText(_translate("Dialog", "9"))
        self.zero.setText(_translate("Dialog", "0"))
        self.enter.setText(_translate("Dialog", "Enter"))
