# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'got_user.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 430)
        Dialog.setStyleSheet("")
        self.user = QtWidgets.QLabel(Dialog)
        self.user.setGeometry(QtCore.QRect(10, 10, 781, 51))
        self.user.setStyleSheet("font-size: 36px;")
        self.user.setObjectName("user")
        self.balance_label = QtWidgets.QLabel(Dialog)
        self.balance_label.setGeometry(QtCore.QRect(30, 100, 291, 31))
        self.balance_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.balance_label.setObjectName("balance_label")
        self.balance = QtWidgets.QLabel(Dialog)
        self.balance.setGeometry(QtCore.QRect(30, 140, 251, 51))
        self.balance.setStyleSheet("font-size: 30px;\n"
"font-weight: bold;\n"
"")
        self.balance.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.balance.setObjectName("balance")
        self.last_order_label = QtWidgets.QLabel(Dialog)
        self.last_order_label.setGeometry(QtCore.QRect(30, 240, 291, 31))
        self.last_order_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.last_order_label.setObjectName("last_order_label")
        self.last_order = QtWidgets.QLabel(Dialog)
        self.last_order.setGeometry(QtCore.QRect(30, 280, 251, 121))
        self.last_order.setStyleSheet("font-size: 30px;\n"
"\n"
"")
        self.last_order.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.last_order.setObjectName("last_order")
        self.stackedWidget = QtWidgets.QStackedWidget(Dialog)
        self.stackedWidget.setGeometry(QtCore.QRect(279, 80, 521, 351))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setObjectName("stackedWidget")
        self.unlocked = QtWidgets.QWidget()
        self.unlocked.setObjectName("unlocked")
        self.textEdit = QtWidgets.QTextEdit(self.unlocked)
        self.textEdit.setGeometry(QtCore.QRect(20, 20, 261, 161))
        self.textEdit.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(78, 154, 6);\n"
"border-radius: 12px;\n"
"padding: 10px;")
        self.textEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit.setLineWidth(0)
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setReadOnly(True)
        self.textEdit.setOverwriteMode(True)
        self.textEdit.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit.setObjectName("textEdit")
        self.cancel_button = QtWidgets.QPushButton(self.unlocked)
        self.cancel_button.setGeometry(QtCore.QRect(20, 200, 471, 121))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.cancel_button.setFont(font)
        icon = QtGui.QIcon.fromTheme("cancel")
        self.cancel_button.setIcon(icon)
        self.cancel_button.setIconSize(QtCore.QSize(46, 46))
        self.cancel_button.setObjectName("cancel_button")
        self.plus_sign_pre = QtWidgets.QLabel(self.unlocked)
        self.plus_sign_pre.setEnabled(False)
        self.plus_sign_pre.setGeometry(QtCore.QRect(290, 40, 81, 111))
        font = QtGui.QFont()
        font.setPointSize(60)
        self.plus_sign_pre.setFont(font)
        self.plus_sign_pre.setTextFormat(QtCore.Qt.PlainText)
        self.plus_sign_pre.setScaledContents(False)
        self.plus_sign_pre.setAlignment(QtCore.Qt.AlignCenter)
        self.plus_sign_pre.setObjectName("plus_sign_pre")
        self.add_milk_pre = QtWidgets.QPushButton(self.unlocked)
        self.add_milk_pre.setGeometry(QtCore.QRect(370, 30, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(4)
        self.add_milk_pre.setFont(font)
        self.add_milk_pre.setStyleSheet("")
        self.add_milk_pre.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/milk-container-crossed.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("res/milk-container-checked.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.add_milk_pre.setIcon(icon)
        self.add_milk_pre.setIconSize(QtCore.QSize(80, 80))
        self.add_milk_pre.setCheckable(True)
        self.add_milk_pre.setChecked(False)
        self.add_milk_pre.setObjectName("add_milk_pre")
        self.stackedWidget.addWidget(self.unlocked)
        self.balance_warning = QtWidgets.QWidget()
        self.balance_warning.setObjectName("balance_warning")
        self.textEdit_2 = QtWidgets.QTextEdit(self.balance_warning)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 10, 471, 171))
        self.textEdit_2.setStyleSheet("background-color: orange;\n"
"border-radius: 12px;\n"
"padding-top: 12px")
        self.textEdit_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_2.setUndoRedoEnabled(False)
        self.textEdit_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit_2.setObjectName("textEdit_2")
        self.dismiss_button = QtWidgets.QPushButton(self.balance_warning)
        self.dismiss_button.setGeometry(QtCore.QRect(20, 200, 471, 121))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.dismiss_button.setFont(font)
        self.dismiss_button.setIconSize(QtCore.QSize(46, 46))
        self.dismiss_button.setObjectName("dismiss_button")
        self.stackedWidget.addWidget(self.balance_warning)
        self.balance_denied = QtWidgets.QWidget()
        self.balance_denied.setObjectName("balance_denied")
        self.textEdit_3 = QtWidgets.QTextEdit(self.balance_denied)
        self.textEdit_3.setGeometry(QtCore.QRect(20, 10, 471, 171))
        self.textEdit_3.setStyleSheet("background-color: red;\n"
"border-radius: 12px;\n"
"padding-top: 12px")
        self.textEdit_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_3.setUndoRedoEnabled(False)
        self.textEdit_3.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit_3.setObjectName("textEdit_3")
        self.dismiss_button_deny = QtWidgets.QPushButton(self.balance_denied)
        self.dismiss_button_deny.setGeometry(QtCore.QRect(20, 200, 471, 121))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.dismiss_button_deny.setFont(font)
        self.dismiss_button_deny.setIconSize(QtCore.QSize(46, 46))
        self.dismiss_button_deny.setObjectName("dismiss_button_deny")
        self.stackedWidget.addWidget(self.balance_denied)
        self.ordered = QtWidgets.QWidget()
        self.ordered.setObjectName("ordered")
        self.coffee_beans = QtWidgets.QLabel(self.ordered)
        self.coffee_beans.setEnabled(True)
        self.coffee_beans.setGeometry(QtCore.QRect(40, 30, 121, 121))
        self.coffee_beans.setStyleSheet("padding: 10px;")
        self.coffee_beans.setText("")
        self.coffee_beans.setPixmap(QtGui.QPixmap("res/coffee-beans.png"))
        self.coffee_beans.setScaledContents(True)
        self.coffee_beans.setObjectName("coffee_beans")
        self.ok_button = QtWidgets.QPushButton(self.ordered)
        self.ok_button.setGeometry(QtCore.QRect(370, 200, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.ok_button.setFont(font)
        self.ok_button.setText("OK")
        self.ok_button.setObjectName("ok_button")
        self.label = QtWidgets.QLabel(self.ordered)
        self.label.setGeometry(QtCore.QRect(70, 200, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.price = QtWidgets.QLabel(self.ordered)
        self.price.setGeometry(QtCore.QRect(210, 200, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.price.setFont(font)
        self.price.setObjectName("price")
        self.milk_price = QtWidgets.QLabel(self.ordered)
        self.milk_price.setEnabled(False)
        self.milk_price.setGeometry(QtCore.QRect(210, 240, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.milk_price.setFont(font)
        self.milk_price.setObjectName("milk_price")
        self.total_price = QtWidgets.QLabel(self.ordered)
        self.total_price.setGeometry(QtCore.QRect(210, 280, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.total_price.setFont(font)
        self.total_price.setObjectName("total_price")
        self.milk_label = QtWidgets.QLabel(self.ordered)
        self.milk_label.setEnabled(False)
        self.milk_label.setGeometry(QtCore.QRect(70, 240, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.milk_label.setFont(font)
        self.milk_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.milk_label.setObjectName("milk_label")
        self.total_label = QtWidgets.QLabel(self.ordered)
        self.total_label.setGeometry(QtCore.QRect(70, 280, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.total_label.setFont(font)
        self.total_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.total_label.setObjectName("total_label")
        self.line = QtWidgets.QFrame(self.ordered)
        self.line.setGeometry(QtCore.QRect(80, 270, 211, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.water_drop = QtWidgets.QLabel(self.ordered)
        self.water_drop.setEnabled(True)
        self.water_drop.setGeometry(QtCore.QRect(40, 30, 121, 121))
        self.water_drop.setStyleSheet("padding: 10px;")
        self.water_drop.setText("")
        self.water_drop.setPixmap(QtGui.QPixmap("res/water-drop.png"))
        self.water_drop.setScaledContents(True)
        self.water_drop.setObjectName("water_drop")
        self.coffee_or_water = QtWidgets.QStackedWidget(self.ordered)
        self.coffee_or_water.setGeometry(QtCore.QRect(170, 10, 351, 171))
        self.coffee_or_water.setObjectName("coffee_or_water")
        self.coffee_page = QtWidgets.QWidget()
        self.coffee_page.setObjectName("coffee_page")
        self.plus_sign = QtWidgets.QLabel(self.coffee_page)
        self.plus_sign.setEnabled(False)
        self.plus_sign.setGeometry(QtCore.QRect(40, 20, 91, 111))
        font = QtGui.QFont()
        font.setPointSize(60)
        self.plus_sign.setFont(font)
        self.plus_sign.setTextFormat(QtCore.Qt.PlainText)
        self.plus_sign.setScaledContents(False)
        self.plus_sign.setAlignment(QtCore.Qt.AlignCenter)
        self.plus_sign.setObjectName("plus_sign")
        self.add_milk = QtWidgets.QPushButton(self.coffee_page)
        self.add_milk.setGeometry(QtCore.QRect(200, 20, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(4)
        self.add_milk.setFont(font)
        self.add_milk.setStyleSheet("")
        self.add_milk.setText("")
        self.add_milk.setIcon(icon)
        self.add_milk.setIconSize(QtCore.QSize(80, 80))
        self.add_milk.setCheckable(True)
        self.add_milk.setChecked(False)
        self.add_milk.setObjectName("add_milk")
        self.coffee_or_water.addWidget(self.coffee_page)
        self.water_page = QtWidgets.QWidget()
        self.water_page.setObjectName("water_page")
        self.label_2 = QtWidgets.QLabel(self.water_page)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 341, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.water_no_button = QtWidgets.QPushButton(self.water_page)
        self.water_no_button.setGeometry(QtCore.QRect(200, 50, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.water_no_button.setFont(font)
        self.water_no_button.setText("NO")
        self.water_no_button.setObjectName("water_no_button")
        self.water_yes_button = QtWidgets.QPushButton(self.water_page)
        self.water_yes_button.setGeometry(QtCore.QRect(60, 50, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.water_yes_button.setFont(font)
        self.water_yes_button.setText("YES")
        self.water_yes_button.setObjectName("water_yes_button")
        self.coffee_or_water.addWidget(self.water_page)
        self.coffee_or_water.raise_()
        self.coffee_beans.raise_()
        self.ok_button.raise_()
        self.label.raise_()
        self.price.raise_()
        self.milk_price.raise_()
        self.total_price.raise_()
        self.milk_label.raise_()
        self.total_label.raise_()
        self.line.raise_()
        self.water_drop.raise_()
        self.stackedWidget.addWidget(self.ordered)
        self.ordered_water = QtWidgets.QWidget()
        self.ordered_water.setObjectName("ordered_water")
        self.water_drop_2 = QtWidgets.QLabel(self.ordered_water)
        self.water_drop_2.setEnabled(True)
        self.water_drop_2.setGeometry(QtCore.QRect(40, 40, 121, 121))
        self.water_drop_2.setStyleSheet("padding: 10px;")
        self.water_drop_2.setText("")
        self.water_drop_2.setPixmap(QtGui.QPixmap("res/water-drop.png"))
        self.water_drop_2.setScaledContents(True)
        self.water_drop_2.setObjectName("water_drop_2")
        self.stackedWidget.addWidget(self.ordered_water)
        self.without_milk_label = QtWidgets.QLabel(Dialog)
        self.without_milk_label.setGeometry(QtCore.QRect(638, 233, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.without_milk_label.setFont(font)
        self.without_milk_label.setAlignment(QtCore.Qt.AlignCenter)
        self.without_milk_label.setObjectName("without_milk_label")
        self.with_milk_label = QtWidgets.QLabel(Dialog)
        self.with_milk_label.setGeometry(QtCore.QRect(638, 233, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.with_milk_label.setFont(font)
        self.with_milk_label.setAlignment(QtCore.Qt.AlignCenter)
        self.with_milk_label.setObjectName("with_milk_label")
        self.with_milk_label.raise_()
        self.without_milk_label.raise_()
        self.user.raise_()
        self.balance_label.raise_()
        self.balance.raise_()
        self.last_order_label.raise_()
        self.last_order.raise_()
        self.stackedWidget.raise_()

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        self.coffee_or_water.setCurrentIndex(0)
        self.add_milk_pre.toggled['bool'].connect(self.plus_sign_pre.setEnabled)
        self.add_milk_pre.toggled['bool'].connect(self.add_milk.setChecked)
        self.add_milk.toggled['bool'].connect(self.milk_label.setEnabled)
        self.add_milk.toggled['bool'].connect(self.milk_price.setEnabled)
        self.add_milk.toggled['bool'].connect(self.plus_sign.setEnabled)
        self.add_milk.toggled['bool'].connect(self.without_milk_label.setHidden)
        self.add_milk.toggled['bool'].connect(self.with_milk_label.setVisible)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.user.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Welcome</p></body></html>"))
        self.balance_label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:22pt; color:#888a85;\">Your balance</span></p></body></html>"))
        self.balance.setText(_translate("Dialog", "TextLabel"))
        self.last_order_label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:22pt; color:#888a85;\">Your last order</span></p></body></html>"))
        self.last_order.setText(_translate("Dialog", "<html><head/><body><p>Time</p><p>Coffee + Milk</p><p>Price</p></body></html>"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt; vertical-align:middle;\">Coffee Machine Unlocked</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:22pt; vertical-align:middle;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt; vertical-align:middle;\">Please Order</span></p></body></html>"))
        self.cancel_button.setText(_translate("Dialog", "Cancel"))
        self.plus_sign_pre.setText(_translate("Dialog", "+"))
        self.textEdit_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt;\">WARNING!<br /></span><span style=\" font-size:22pt; font-weight:600;\">Your account is about to be locked.<br /></span><span style=\" font-size:16pt;\">Please recharge your balance to avoid this.<br />You can also buy milk to do so.</span></p></body></html>"))
        self.dismiss_button.setText(_translate("Dialog", "Dismiss"))
        self.textEdit_3.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt;\">SORRY!<br /></span><span style=\" font-size:22pt; font-weight:600;\">Your account is locked.<br /></span><span style=\" font-size:16pt;\">Please recharge your balance to unlock it.<br />You can also buy milk to do so.</span></p></body></html>"))
        self.dismiss_button_deny.setText(_translate("Dialog", "Dismiss"))
        self.label.setText(_translate("Dialog", "Coffee"))
        self.price.setText(_translate("Dialog", "0.20€"))
        self.milk_price.setText(_translate("Dialog", "0.10€"))
        self.total_price.setText(_translate("Dialog", "0.30€"))
        self.milk_label.setText(_translate("Dialog", "Milk"))
        self.total_label.setText(_translate("Dialog", "Total"))
        self.plus_sign.setText(_translate("Dialog", "+"))
        self.label_2.setText(_translate("Dialog", "Did you order water?"))
        self.without_milk_label.setText(_translate("Dialog", "Without Milk"))
        self.with_milk_label.setText(_translate("Dialog", "With Milk"))
