# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CoffeeTimeAndroid.ui'
#
# Created: Tue May 16 10:02:49 2017
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 430)
        Dialog.setStyleSheet("background-color : rgb(217, 203, 174)")
        self.downloadButton = QtWidgets.QCommandLinkButton(Dialog)
        self.downloadButton.setGeometry(QtCore.QRect(230, 120, 125, 171))
        self.downloadButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.downloadButton.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.downloadButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../res/downloadNotSelected.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downloadButton.setIcon(icon)
        self.downloadButton.setIconSize(QtCore.QSize(110, 150))
        self.downloadButton.setObjectName("downloadButton")
        self.registerButton = QtWidgets.QCommandLinkButton(Dialog)
        self.registerButton.setGeometry(QtCore.QRect(450, 120, 125, 171))
        self.registerButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.registerButton.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.registerButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../res/addUserNotSelected.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.registerButton.setIcon(icon1)
        self.registerButton.setIconSize(QtCore.QSize(110, 150))
        self.registerButton.setObjectName("registerButton")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(Dialog)
        self.commandLinkButton.setGeometry(QtCore.QRect(0, 240, 201, 191))
        self.commandLinkButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.commandLinkButton.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.commandLinkButton.setStyleSheet(":hover { background-color : rgb(0,0,0,0)}")
        self.commandLinkButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../res/phoneJoke.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton.setIcon(icon2)
        self.commandLinkButton.setIconSize(QtCore.QSize(240, 190))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(290, 30, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit.setStyleSheet("border : 3px solid rgb(71,43,27);\n"
"border-radius : 10px;\n"
"background-color : rgb(217, 203, 174);\n"
"color : rgb(72, 43, 27)")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.qrWidget = QtWidgets.QWidget(Dialog)
        self.qrWidget.setGeometry(QtCore.QRect(0, 90, 800, 341))
        self.qrWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.qrWidget.setStyleSheet("border:none")
        self.qrWidget.setObjectName("qrWidget")
        self.qrHide = QtWidgets.QCommandLinkButton(self.qrWidget)
        self.qrHide.setGeometry(QtCore.QRect(0, 0, 800, 341))
        self.qrHide.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qrHide.setText("")
        icon = QtGui.QIcon.fromTheme("emtpy")
        self.qrHide.setIcon(icon)
        self.qrHide.setObjectName("qrHide")
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.qrWidget)
        self.commandLinkButton_2.setGeometry(QtCore.QRect(300, 60, 221, 221))
        self.commandLinkButton_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../res/download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton_2.setIcon(icon3)
        self.commandLinkButton_2.setIconSize(QtCore.QSize(200, 200))
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.addWidget = QtWidgets.QWidget(Dialog)
        self.addWidget.setGeometry(QtCore.QRect(0, 90, 800, 341))
        self.addWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.addWidget.setStyleSheet("border:none")
        self.addWidget.setObjectName("addWidget")
        self.addHide = QtWidgets.QCommandLinkButton(self.addWidget)
        self.addHide.setGeometry(QtCore.QRect(0, 0, 800, 341))
        self.addHide.setFocusPolicy(QtCore.Qt.NoFocus)
        self.addHide.setText("")
        icon = QtGui.QIcon.fromTheme("emtpy")
        self.addHide.setIcon(icon)
        self.addHide.setObjectName("addHide")
        self.userQr = QtWidgets.QCommandLinkButton(self.addWidget)
        self.userQr.setGeometry(QtCore.QRect(300, 60, 221, 221))
        self.userQr.setFocusPolicy(QtCore.Qt.NoFocus)
        self.userQr.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../res/addUserWaiting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.userQr.setIcon(icon4)
        self.userQr.setIconSize(QtCore.QSize(200, 200))
        self.userQr.setObjectName("userQr")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lineEdit.setText(_translate("Dialog", "App Center"))

