# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CoffeeTime.ui'
#
# Created: Fri Dec  9 21:02:04 2016
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 480)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet("background : rgb(217, 203, 174);\n"
"border: none;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.menu = QtWidgets.QWidget(self.centralwidget)
        self.menu.setGeometry(QtCore.QRect(0, 0, 141, 491))
        self.menu.setStyleSheet("background:rgb(72, 43, 27)")
        self.menu.setObjectName("menu")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.menu)
        self.lineEdit_2.setGeometry(QtCore.QRect(0, 0, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("color : white;\n"
"background-color : #3f2a14")
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.menu)
        self.commandLinkButton_2.setGeometry(QtCore.QRect(30, 390, 81, 91))
        self.commandLinkButton_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.commandLinkButton_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.commandLinkButton_2.setStyleSheet(":hover { background-color : rgb(0,0,0,0)}")
        self.commandLinkButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../res/coffee.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton_2.setIcon(icon)
        self.commandLinkButton_2.setIconSize(QtCore.QSize(80, 80))
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.menu)
        self.pushButton_2.setGeometry(QtCore.QRect(-3, 50, 141, 31))
        self.pushButton_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.pushButton_2.setStyleSheet("color : rgba(255,255,255,90);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../res/homeIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(15, 15))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.menu)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 100, 141, 31))
        self.pushButton_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.pushButton_3.setStyleSheet("color : rgba(255,255,255,90);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../res/androidIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(15, 15))
        self.pushButton_3.setObjectName("pushButton_3")
        self.menuButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.menuButton.setGeometry(QtCore.QRect(141, 0, 41, 41))
        self.menuButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.menuButton.setStyleSheet(":hover { background-color : rgb(0,0,0,0)}")
        self.menuButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../res/menuIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuButton.setIcon(icon3)
        self.menuButton.setObjectName("menuButton")
        self.coffeeOrder = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.coffeeOrder.setGeometry(QtCore.QRect(490, 140, 125, 167))
        self.coffeeOrder.setFocusPolicy(QtCore.Qt.NoFocus)
        self.coffeeOrder.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.coffeeOrder.setStyleSheet(":hover { background-color : rgb(0,0,0,0)}")
        self.coffeeOrder.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../res/coffeeSelected.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon4.addPixmap(QtGui.QPixmap("../res/coffeeSelected.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap("../res/coffeeSelected.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        icon4.addPixmap(QtGui.QPixmap("../res/coffeeNotSelected.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.coffeeOrder.setIcon(icon4)
        self.coffeeOrder.setIconSize(QtCore.QSize(110, 150))
        self.coffeeOrder.setObjectName("coffeeOrder")
        self.waterOrder = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.waterOrder.setGeometry(QtCore.QRect(310, 140, 125, 167))
        self.waterOrder.setFocusPolicy(QtCore.Qt.NoFocus)
        self.waterOrder.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.waterOrder.setStyleSheet(":hover { background-color : rgb(0,0,0,0)}")
        self.waterOrder.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../res/waterNotSelected.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.waterOrder.setIcon(icon5)
        self.waterOrder.setIconSize(QtCore.QSize(110, 150))
        self.waterOrder.setObjectName("waterOrder")
        self.addMilk = QtWidgets.QPushButton(self.centralwidget)
        self.addMilk.setEnabled(False)
        self.addMilk.setGeometry(QtCore.QRect(500, 340, 111, 26))
        self.addMilk.setFocusPolicy(QtCore.Qt.NoFocus)
        self.addMilk.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.addMilk.setStyleSheet("border: 1px solid white;\n"
"background: rgb();\n"
"border-radius: 10px;\n"
"")
        self.addMilk.setCheckable(False)
        self.addMilk.setObjectName("addMilk")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(535, 300, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit.setStyleSheet("color : rgb(72, 43, 27);\n"
"border : none;\n"
"")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(310, 420, 316, 60))
        self.pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.pushButton.setStyleSheet(":hover { background-color : rgb(217, 203, 174)}\n"
"")
        self.pushButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../res/orderBar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon6)
        self.pushButton.setIconSize(QtCore.QSize(316, 60))
        self.pushButton.setObjectName("pushButton")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton.setGeometry(QtCore.QRect(740, 0, 41, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandLinkButton.sizePolicy().hasHeightForWidth())
        self.commandLinkButton.setSizePolicy(sizePolicy)
        self.commandLinkButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.commandLinkButton.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.commandLinkButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../res/settingsButton.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton.setIcon(icon7)
        self.commandLinkButton.setIconSize(QtCore.QSize(30, 30))
        self.commandLinkButton.setObjectName("commandLinkButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_2.setText(_translate("MainWindow", "    Coffee Time"))
        self.pushButton_2.setText(_translate("MainWindow", "Main menu"))
        self.pushButton_3.setText(_translate("MainWindow", "Android app"))
        self.addMilk.setText(_translate("MainWindow", "Milk"))
        self.lineEdit.setText(_translate("MainWindow", " +"))

