# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CoffeeTimeAdminLogin.ui'
#
# Created: Mon May 29 12:04:18 2017
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(659, 480)
        Dialog.setStyleSheet("background : rgb(217, 203, 174)")
        self.one = QtWidgets.QCommandLinkButton(Dialog)
        self.one.setGeometry(QtCore.QRect(210, 130, 72, 75))
        self.one.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.one.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../res/1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.one.setIcon(icon)
        self.one.setIconSize(QtCore.QSize(60, 60))
        self.one.setObjectName("one")
        self.two = QtWidgets.QCommandLinkButton(Dialog)
        self.two.setGeometry(QtCore.QRect(290, 130, 72, 75))
        self.two.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.two.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../res/2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.two.setIcon(icon1)
        self.two.setIconSize(QtCore.QSize(60, 60))
        self.two.setObjectName("two")
        self.three = QtWidgets.QCommandLinkButton(Dialog)
        self.three.setGeometry(QtCore.QRect(370, 130, 72, 75))
        self.three.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.three.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../res/3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.three.setIcon(icon2)
        self.three.setIconSize(QtCore.QSize(60, 60))
        self.three.setObjectName("three")
        self.four = QtWidgets.QCommandLinkButton(Dialog)
        self.four.setGeometry(QtCore.QRect(210, 210, 72, 75))
        self.four.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.four.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../res/4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.four.setIcon(icon3)
        self.four.setIconSize(QtCore.QSize(60, 60))
        self.four.setObjectName("four")
        self.six = QtWidgets.QCommandLinkButton(Dialog)
        self.six.setGeometry(QtCore.QRect(370, 210, 72, 75))
        self.six.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.six.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../res/6.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.six.setIcon(icon4)
        self.six.setIconSize(QtCore.QSize(60, 60))
        self.six.setObjectName("six")
        self.five = QtWidgets.QCommandLinkButton(Dialog)
        self.five.setGeometry(QtCore.QRect(290, 210, 72, 75))
        self.five.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.five.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../res/5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.five.setIcon(icon5)
        self.five.setIconSize(QtCore.QSize(60, 60))
        self.five.setObjectName("five")
        self.seven = QtWidgets.QCommandLinkButton(Dialog)
        self.seven.setGeometry(QtCore.QRect(210, 290, 72, 75))
        self.seven.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.seven.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../res/7.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.seven.setIcon(icon6)
        self.seven.setIconSize(QtCore.QSize(60, 60))
        self.seven.setObjectName("seven")
        self.eight = QtWidgets.QCommandLinkButton(Dialog)
        self.eight.setGeometry(QtCore.QRect(290, 290, 72, 75))
        self.eight.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.eight.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../res/8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eight.setIcon(icon7)
        self.eight.setIconSize(QtCore.QSize(60, 60))
        self.eight.setObjectName("eight")
        self.nine = QtWidgets.QCommandLinkButton(Dialog)
        self.nine.setGeometry(QtCore.QRect(370, 290, 72, 75))
        self.nine.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.nine.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../res/9.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nine.setIcon(icon8)
        self.nine.setIconSize(QtCore.QSize(60, 60))
        self.nine.setObjectName("nine")
        self.zero = QtWidgets.QCommandLinkButton(Dialog)
        self.zero.setGeometry(QtCore.QRect(290, 370, 72, 75))
        self.zero.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.zero.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../res/0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zero.setIcon(icon9)
        self.zero.setIconSize(QtCore.QSize(60, 60))
        self.zero.setObjectName("zero")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(210, 30, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit.setStyleSheet("border : 3px solid rgb(71,43,27);\n"
"border-radius : 10px;\n"
"background-color : rgb(217, 203, 174);\n"
"color : rgb(72, 43, 27);")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.clear = QtWidgets.QCommandLinkButton(Dialog)
        self.clear.setGeometry(QtCore.QRect(210, 370, 72, 75))
        self.clear.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.clear.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../res/clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clear.setIcon(icon10)
        self.clear.setIconSize(QtCore.QSize(60, 60))
        self.clear.setObjectName("clear")
        self.enter = QtWidgets.QCommandLinkButton(Dialog)
        self.enter.setGeometry(QtCore.QRect(370, 370, 72, 75))
        self.enter.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.enter.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../res/enter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.enter.setIcon(icon11)
        self.enter.setIconSize(QtCore.QSize(60, 60))
        self.enter.setObjectName("enter")
        self.backHome = QtWidgets.QPushButton(Dialog)
        self.backHome.setGeometry(QtCore.QRect(530, 40, 91, 31))
        self.backHome.setStyleSheet("border : 3px solid rgb(71,43,27);\n"
"border-radius : 10px;\n"
"background-color : rgb(217, 203, 174);\n"
"color : rgb(72, 43, 27);")
        self.backHome.setObjectName("backHome")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lineEdit.setText(_translate("Dialog", " Admin Login"))
        self.backHome.setText(_translate("Dialog", "Home page"))

